ealcobaca/pymfe

python/pymfe/_summary.py
python/pymfe/general.py
python/pymfe/mfe.py
python/tests/context.py
python/tests/test_datasets/fabricated.csv
python/tests/test_general.py

Adding:
- General metafeatures methods implementation (general.py module)
- Tests for General metafeatures based in the original mfe R implementation (with rpy2 bib)
- and some necessary changes in some modules after General metafeatures testing.

Mtfeat general

---

.travis.yml
python/pymfe/_internal.py
python/pymfe/_summary.py
python/pymfe/general.py
python/pymfe/info_theory.py
python/pymfe/mfe.py
python/pymfe/statistical.py
python/requirements.txt
python/tests/context.py
python/tests/test_mfe.py
python/tests/test_statistical.py

- Added precomputation framework, to avoid repeated computations
- An improvement in the normality test method
- Huge improvement in documentation
- Some varied smaller code fixes

Precomputation

---

.travis.yml
pymfe/landmarking.py
pymfe/model_based.py
tests/test_general.py
tests/utils.py

- test of general meta-features.
- pytest running on Travis.
- fix bug in the model-based and landmarking modules.

Test of general meta-features

---

pymfe/general.py
pymfe/info_theory.py
pymfe/landmarking.py
pymfe/mfe.py
pymfe/model_based.py
pymfe/statistical.py
tests/test_general.py
tests/utils.py

- Fixed some glitches due to data transformations (binarization and discretization) in General metafeatures.
- Improved some docs
- Used Yapf in some source files

General mtf fixes

---

tests/test_infotheo.py
tests/test_statistical.py

- Added info-theory test module. Tests are all OK with Numerical and Categorical data, but some fail for Mixed data. This must be investigated and addressed in further updates.
- Some small fixes in the statistical test module.

Updating tests

---

pymfe/_internal.py
pymfe/landmarking.py
pymfe/mfe.py

- Added support for postprocessing methods (prefixed with "postprocess_", defined inside "_internal.py")

Postprocessing

---

pymfe/_internal.py
tests/test_architecture.py

- Added some architecture tests to improve code coverage.

Postprocessing (code coverage)

---

.readthedocs.yml
requirements.docs.txt
setup.py

fixing docs error

---

examples/03_miscellaneous_examples/plot_listing_metafeatures_groups.py
examples/03_miscellaneous_examples/plot_metafeature_description.py
pymfe/_internal.py
pymfe/clustering.py
pymfe/mfe.py
requirements.txt
setup.py
tests/test_architecture.py

New features
----------------
* minor fix
* metafeature description 
* metafeature description example

Mf listing

---

CONTRIBUTING.md
Makefile

Ad minor changes in contribution.md text.

Better Makefile to avoid problems with venv inside project folder.

---

pymfe/_internal.py
pymfe/clustering.py
pymfe/complexity.py
pymfe/general.py
pymfe/info_theory.py
pymfe/itemset.py
pymfe/landmarking.py
pymfe/mfe.py
pymfe/model_based.py
pymfe/relative.py
pymfe/scoring.py
pymfe/statistical.py

- Added at least one reference for each metafeature
- Several updates in all sorts of pydocs

Metafeature references & more pydoc updates

---

docs/Makefile
docs/source/api.rst
docs/source/conf.py
docs/source/index.rst
docs/source/pages/run.py
examples/01_introductory_examples/plot_groups.py
examples/01_introductory_examples/plot_summary.py
examples/03_miscellaneous_examples/plot_metafeature_description.py
examples/README.txt
pymfe/clustering.py
pymfe/complexity.py
pymfe/concept.py
pymfe/general.py
pymfe/info_theory.py
pymfe/itemset.py
pymfe/landmarking.py
pymfe/mfe.py
pymfe/model_based.py
pymfe/statistical.py
tests/test_architecture.py

Update in the meta-feature description.
Update in the online documentation.
Meta-feature table added in the online documentation.
Update in docstrings.

Mtf description

---

Makefile
pymfe/_version.py
requirements-dev.txt
requirements-docs.txt

Makefile updated.
New version tagged (0.2.0).

New version

---

README.md
examples/01_introductory_examples/plot_pymfe_default.py
examples/README.txt
pymfe/mfe.py

* All meta-feature groups are updated in "README.md".
* The default value for MFE is now 'default' in favor of "all".
* The extraction example of groups was updated.

Minor updates

---

docs/source/about.rst
docs/source/api.rst
docs/source/index.rst
docs/source/install.rst
docs/source/new.rst
docs/source/using.rst
examples/01_introductory_examples/README.txt
examples/01_introductory_examples/plot_pymfe_default.py
examples/01_introductory_examples/plot_pymfe_specific.py
examples/01_introductory_examples/plot_summary.py
examples/02_advanced_examples/plot_custom_arguments.py
examples/03_miscellaneous_examples/plot_listing_metafeatures_groups.py
examples/03_miscellaneous_examples/plot_using_pandas_csv_arff.py
examples/README.txt
pymfe/clustering.py

Online documentation improvement
-----------------------------------------------
* References to PyPI and GitHub added
* Pages revised and improved
* Fixed problems with header style '=' or '-'
* Added news about the release 0.2.0
* Changed name pymfe to PyMFE

Online doc fix

---

docs/source/conf.py

Meta-feature table is now fixed

Meta-feature's table is now wide

---

README.md

Added Pymfe accepted JMLR paper as the citation paper on README file.

Added accepted JMLR citation paper on README

---

.travis.yml
Makefile
README.md
pymfe/__init__.py
pymfe/_dev.py
pymfe/_internal.py
pymfe/_summary.py
pymfe/_version.py
pymfe/clustering.py
pymfe/complexity.py
pymfe/concept.py
pymfe/general.py
pymfe/info_theory.py
pymfe/itemset.py
pymfe/landmarking.py
pymfe/mfe.py
pymfe/model_based.py
pymfe/relative.py
pymfe/statistical.py
requirements-dev.txt
requirements.txt
setup.py
tests/test_architecture.py
tests/test_output.py
tests/test_statistical.py

Provided a full code maintenance, which consists of the following items:
- Changed version '0.4' -> '0.4.1'
- Added Python 3.9 to tests.
- Fixed all static code analysis/object type errors to conform to the most recent mypy standards.
- Reformatted all code using the most recent Black format standards.
- Rewrote a few lines of code to avoid deprecation warnings of some dependency packages.
- Rewrote a few lines of code to correct results due to changes in recent versions of some dependency packages (mainly sklearn).
- Removed custom progress bar, now using [tqdm](https://github.com/tqdm/tqdm). Still available whenever verbose level is exactly 1.
- Now executing pytest and pylint in parallel.
- Added one more example in README.md of using methods to llist pymfe available resources …

Full code maintenance

---

tests/test_output.py

Added tests to test different output types.

Add tests for different 'extract' and 'extract_with_confidence' output types

---

.gitignore
Makefile
README.md
docs/source/conf.py
docs/source/install.rst
docs/source/pages/run.py
docs/sphinxext/github_link.py
examples/01_introductory_examples/plot_pymfe_specific.py
pymfe/mfe.py
requirements-dev.txt
setup.py
tests/test_architecture.py
tests/test_clustering.py
tests/test_complexity.py
tests/test_concept.py
tests/test_errors_warnings.py
tests/test_general.py
tests/test_infotheo.py
tests/test_itemset.py
tests/test_landmarking.py
tests/test_model_based.py
tests/test_output.py
tests/test_relative_landmarking.py
tests/test_scaling.py
tests/test_statistical.py
tests/test_summary.py
tests/test_system_testing.py
tests/utils.py

Dear @FelSiq,
I think everything needed for the new version 0.4.1 was done.
In summary, this PR will:
- Update the documentation
- Fix some documentation bugs
- Update python codes from docs/ and test/ by using Black code formatter
- Update requirements
- Update makefile
If everything sounds good for you thus I will create the new 0.4.1 version :)
This PR will solve #111 and #117
Best regards,
Edesio

Release 0.4.1

---

pymfe/complexity.py
pymfe/mfe.py
requirements.txt
setup.py

Fixes #123.
Fix errors regarding igraph classes and attributes as per #123 .
@viniciusfleury could you verify if these updates solved the issue?

update: fix issues from new version of igraph

---

examples/03_miscellaneous_examples/plot_extraction_total_elapsed_time.py

doc: quickfix example title format
